services:
  database:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: "zeyneptekin"
      MONGO_INITDB_ROOT_PASSWORD: "123456"
    ports:
      - "27017:27017"
    networks:
      - backend

  web_scraping:
    build:
      context: web_scraping
      dockerfile: Dockerfile
    container_name: web_scraping_service
    depends_on:
      - database
    networks:
      - backend

  api:
    build:
      context: api
      dockerfile: Dockerfile
    container_name: api_service
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - backend
      - frontend

  web:
    build:
      context: web
      dockerfile: Dockerfile
    container_name: web_service
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - backend
      - frontend

networks:
  frontend:
    external: false
  backend:
    external: false
