services:
  database:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"

  cron:
    build:
      context: ./src/cron
      dockerfile: ./Dockerfile
    volumes:
      - ./src/web_scraping:/app/web_scraping
    container_name: cron_service
    restart: always

  webscraping:
    build:
      context: ./src/web_scraping
      dockerfile: Dockerfile
    container_name: web_scraping_service
    depends_on:
      - cron
